name: Trigger Action with cron
on:
  push:
    branches:
      - main
  schedule:
  #RUN  AT 5 AM EVERY WEEK DAY FROM MONDAY TO FRIDAY
    - cron: '0 5 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: | 
        echo "Running!"
